CREATE TABLE `star_orbital_characteristic_data`
(
  `Star`                       varchar(20) NOT NULL,
  `Aphelion`                   varchar(20) DEFAULT NULL,
  `AphelionUnit`               varchar(5) DEFAULT NULL,
  `Perihelion`                 varchar(20) DEFAULT NULL,
  `PerihelionUnit`             varchar(5) DEFAULT NULL,
  `SemiMajorAxis`              varchar(20) DEFAULT NULL,
  `SemiMajorAxisUnit`          varchar(5) DEFAULT NULL,
  `Eccentricity`               varchar(20) DEFAULT NULL,
  `SiderealOrbitalPeriod`      varchar(20) DEFAULT NULL,
  `SiderealOrbitalPeriodUnit`  varchar(5) DEFAULT NULL,
  `SynodicOrbitalPeriod`      varchar(20) DEFAULT NULL,
  `SynodicOrbitalPeriodUnit`  varchar(5) DEFAULT NULL,
  `AverageOrbitalSpeed`        varchar(20) DEFAULT NULL,
  `AverageOrbitalSpeedUnit`    varchar(5) DEFAULT NULL,
  `MeanAnomaly`                varchar(20) DEFAULT NULL,
  `MeanAnomalyUnit`            varchar(5) DEFAULT NULL,
  `Inclination`                varchar(20) DEFAULT NULL,
  `InclinationUnit`            varchar(5) DEFAULT NULL,
  `LongitudeOfNode`            varchar(20) DEFAULT NULL,
  `LongitudeOfNodeUnit`        varchar(5) DEFAULT NULL,
  `ArgumentOfPerihelion`       varchar(20) DEFAULT NULL,
  `ArgumentOfPerihelionUnit`   varchar(5) DEFAULT NULL,
  `CreatedDateTime`            varchar(20) DEFAULT NULL,
  `LastModifiedDateTime`       varchar(20) DEFAULT NULL,
    PRIMARY KEY (`Star`),
    CONSTRAINT `StarOrbitalCharacteristicData_fk` FOREIGN KEY (`Star`) REFERENCES `star_general_data` (`Star`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
